<<<<<<< HEAD
from pydantic import BaseModel, Field, validator
from typing import List, Literal
from enum import Enum
=======
from typing import List, Literal, Optional
from pydantic import BaseModel, Field, validator
from enum import Enum
from src.models.clarification import ClarificationRequest
>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e

class AgentType(str, Enum):
    """Available agents for the orchestrator to call.
    
    Numeric mapping:
<<<<<<< HEAD
=======
        0 = general_chat
>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e
        1 = activity_to_law
        2 = procedural_guidance
        3 = draft_builder
        4 = educational_layer
        5 = case_retriever
        6 = comparative_module
    """
<<<<<<< HEAD
=======
    GENERAL_CHAT = "general_chat"
>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e
    ACTIVITY_TO_LAW = "activity_to_law"
    PROCEDURAL_GUIDANCE = "procedural_guidance"
    DRAFT_BUILDER = "draft_builder"
    EDUCATIONAL_LAYER = "educational_layer"
    CASE_RETRIEVER = "case_retriever"
    COMPARATIVE_MODULE = "comparative_module"
    
    @classmethod
    def from_number(cls, num: int) -> "AgentType":
<<<<<<< HEAD
        """Convert numeric agent ID (1-6) to AgentType enum.
=======
        """Convert numeric agent ID (0-6) to AgentType enum.
>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e
        
        Args:
            num: Agent number (1-6)
            
        Returns:
            Corresponding AgentType enum value
            
        Raises:
            ValueError: If num is not between 1 and 6
        """
        mapping = {
<<<<<<< HEAD
=======
            0: cls.GENERAL_CHAT,
>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e
            1: cls.ACTIVITY_TO_LAW,
            2: cls.PROCEDURAL_GUIDANCE,
            3: cls.DRAFT_BUILDER,
            4: cls.EDUCATIONAL_LAYER,
            5: cls.CASE_RETRIEVER,
            6: cls.COMPARATIVE_MODULE,
        }
        if num not in mapping:
<<<<<<< HEAD
            raise ValueError(f"Agent number must be 1-6, got {num}")
=======
            raise ValueError(f"Agent number must be 0-6, got {num}")
>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e
        return mapping[num]
    
    @classmethod
    def to_number(cls, agent: "AgentType") -> int:
<<<<<<< HEAD
        """Convert AgentType enum to numeric ID (1-6).
=======
        """Convert AgentType enum to numeric ID (0-6).
>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e
        
        Args:
            agent: AgentType enum value
            
        Returns:
            Corresponding numeric ID
        """
        mapping = {
<<<<<<< HEAD
=======
            cls.GENERAL_CHAT: 0,
>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e
            cls.ACTIVITY_TO_LAW: 1,
            cls.PROCEDURAL_GUIDANCE: 2,
            cls.DRAFT_BUILDER: 3,
            cls.EDUCATIONAL_LAYER: 4,
            cls.CASE_RETRIEVER: 5,
            cls.COMPARATIVE_MODULE: 6,
        }
        return mapping[agent]

class NextModule(BaseModel):
    """The next module (agent) selected by the orchestrator."""
<<<<<<< HEAD
    agent_number: int = Field(..., description="Numeric ID of the agent to call (1-6).")
=======
    agent_number: int = Field(..., description="Numeric ID of the agent to call (0-6).")
>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e
    reasoning: str = Field(..., description="Why this agent is chosen for the current query.")
    
    @validator('agent_number')
    def validate_agent_number(cls, v):
<<<<<<< HEAD
        """Ensure agent_number is between 1 and 6."""
        if not isinstance(v, int) or v < 1 or v > 6:
            raise ValueError(f"agent_number must be an integer between 1 and 6, got {v}")
=======
        """Ensure agent_number is between 0 and 6."""
        if not isinstance(v, int) or v < 0 or v > 6:
            raise ValueError(f"agent_number must be an integer between 0 and 6, got {v}")
>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e
        return v

class OrchestratorPlan(BaseModel):
    """The plan generated by the Orchestrator Agent."""
<<<<<<< HEAD
    next_module: NextModule = Field(..., description="The single next module to execute.")
=======
    next_module: Optional[NextModule] = Field(None, description="The single next module to execute. Required if no clarification is needed.")
    clarification: Optional[ClarificationRequest] = Field(None, description="Request for clarification if the query is ambiguous.")
    legal_domain: Literal["civil", "criminal", "both"] = Field(
        ..., 
        description="The legal domain of the query. 'both' if it involves elements of both (e.g. assault + eviction)."
    )

>>>>>>> 14a165ddc199668c3ad8563ab4d99d899b1c0e5e
