from pydantic import BaseModel, Field
from typing import List, Literal
from enum import Enum

class AgentType(str, Enum):
    """Available agents for the orchestrator to call."""
    ACTIVITY_TO_LAW = "activity_to_law"
    PROCEDURAL_GUIDANCE = "procedural_guidance"
    DRAFT_BUILDER = "draft_builder"
    EDUCATIONAL_LAYER = "educational_layer"
    CASE_RETRIEVER = "case_retriever"
    COMPARATIVE_MODULE = "comparative_module"

class NextStep(BaseModel):
    """A single step in the orchestration plan."""
    agent_id: AgentType = Field(..., description="The ID of the agent to call.")
    reasoning: str = Field(..., description="Why this agent is needed for the current query.")

class OrchestratorPlan(BaseModel):
    """The plan generated by the Orchestrator Agent."""
    steps: List[NextStep] = Field(..., description="List of agents to call in order.")
    final_response_needed: bool = Field(True, description="Whether to synthesize a final response after steps.")
